// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.37.1. DO NOT EDIT.

package aws

import (
	context "context"

	resourcetags "github.com/elastic/cloudbeat/internal/resources/providers/awslib/resourcetags"
	mock "github.com/stretchr/testify/mock"
)

// mockResourceTagsProvider is an autogenerated mock type for the resourceTagsProvider type
type mockResourceTagsProvider struct {
	mock.Mock
}

type mockResourceTagsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockResourceTagsProvider) EXPECT() *mockResourceTagsProvider_Expecter {
	return &mockResourceTagsProvider_Expecter{mock: &_m.Mock}
}

// GetResources provides a mock function with given fields: ctx
func (_m *mockResourceTagsProvider) GetResources(ctx context.Context) ([]resourcetags.Resource, error) {
	ret := _m.Called(ctx)

	var r0 []resourcetags.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]resourcetags.Resource, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []resourcetags.Resource); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourcetags.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockResourceTagsProvider_GetResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResources'
type mockResourceTagsProvider_GetResources_Call struct {
	*mock.Call
}

// GetResources is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockResourceTagsProvider_Expecter) GetResources(ctx interface{}) *mockResourceTagsProvider_GetResources_Call {
	return &mockResourceTagsProvider_GetResources_Call{Call: _e.mock.On("GetResources", ctx)}
}

func (_c *mockResourceTagsProvider_GetResources_Call) Run(run func(ctx context.Context)) *mockResourceTagsProvider_GetResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockResourceTagsProvider_GetResources_Call) Return(_a0 []resourcetags.Resource, _a1 error) *mockResourceTagsProvider_GetResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockResourceTagsProvider_GetResources_Call) RunAndReturn(run func(context.Context) ([]resourcetags.Resource, error)) *mockResourceTagsProvider_GetResources_Call {
	_c.Call.Return(run)
	return _c
}

// newMockResourceTagsProvider creates a new instance of mockResourceTagsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockResourceTagsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockResourceTagsProvider {
	mock := &mockResourceTagsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
